icacls webs /remove:d MINT14
icacls sources /remove:d MINT14
icacls Scripts /remove:d MINT14
icacls PHP /remove:d MINT14
icacls MySQL-Data /remove:d MINT14
icacls MINT14-backup /remove:d MINT14
icacls MINT14-backup /remove:d MINT14
icacls CertidocCtCloudManager-v1.0.6.0 /remove:d MINT14
icacls CertidocCtCloudManager /remove:d MINT14